# Generated by Django 5.2.7 on 2025-10-16 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinica',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atencion', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('diagnostico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoClinico',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('archivo', models.BinaryField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.historialclinica')),
            ],
        ),
        migrations.AddField(
            model_name='historialclinica',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
