# Generated by Django 5.2.7 on 2025-10-21 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivoclinico',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='archivoclinico',
            name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='archivoclinico',
            name='id_archivo',
        ),
        migrations.RemoveField(
            model_name='archivoclinico',
            name='id_historial',
        ),
        migrations.RemoveField(
            model_name='archivoclinico',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='archivoclinico',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='archivoclinico',
            name='fechaAdjunto',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='archivoclinico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='archivoclinico',
            name='nombreArchivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivoclinico',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='archivoclinico',
            name='rutaArchivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_clinicos/'),
        ),
        migrations.AddField(
            model_name='archivoclinico',
            name='tipoDocumento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
