# Generated by Django 5.2.6 on 2025-11-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_y_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='stock_posterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
