# Generated by Django 5.2.6 on 2025-11-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_y_compras', '0003_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
    ]
