# Generated by Django 5.2.7 on 2025-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_y_personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='usuario_default', max_length=255, unique=True),
        ),
    ]
