# Generated by Django 5.2.7 on 2025-10-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_y_personal', '0002_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
