# Generated by Django 5.2.7 on 2025-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_y_personal', '0003_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
