# Generated by Django 5.2.6 on 2025-11-26 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0003_alter_tratamiento_fecha_inicio'),
        ('facturacion_y_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_atencion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='atencion.atencion'),
        ),
    ]
