# Generated by Django 5.2.6 on 2025-11-27 02:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad_y_personal', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFinanciero',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Reporte Financiero', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_facturas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_compras', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('detalles_por_procedimiento', models.JSONField(blank=True, default=dict)),
                ('detalles_por_insumo', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', max_length=50)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_financieros', to='seguridad_y_personal.usuario')),
            ],
            options={
                'verbose_name': 'Reporte Financiero',
                'verbose_name_plural': 'Reportes Financieros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
