# Generated by Django 5.2.6 on 2025-11-27 03:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_alter_cita_estado'),
        ('reportes', '0001_initial'),
        ('seguridad_y_personal', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaReporte',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('financiero', 'Reporte Financiero'), ('clinico', 'Reporte Clínico'), ('default', 'Reporte Default')], max_length=50)),
                ('objeto_id', models.IntegerField()),
                ('palabras_clave', models.TextField(blank=True, help_text='Separadas por comas')),
                ('etiquetas', models.CharField(blank=True, max_length=255)),
                ('descripcion_indexada', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Reporte',
                'verbose_name_plural': 'Meta Reportes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo_reporte', '-created_at'], name='reportes_me_tipo_re_a4387c_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='reportes_me_fecha_i_b9a50b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReporteClinico',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Reporte Clínico', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_cita', models.CharField(blank=True, choices=[('consulta', 'Consulta'), ('procedimiento', 'Procedimiento'), ('seguimiento', 'Seguimiento'), ('emergencia', 'Emergencia'), ('todas', 'Todas')], default='todas', max_length=50)),
                ('total_citas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('citas_completadas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('citas_canceladas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('citas_reprogramadas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_atenciones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_promedio_atencion', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_procedimientos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('procedimientos_por_tipo', models.JSONField(blank=True, default=dict)),
                ('total_pacientes_atendidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pacientes_nuevos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pacientes_recurrentes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', max_length=50)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_clinicos', to='seguridad_y_personal.usuario')),
                ('id_odontologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_clinicos', to='citas.odontologo')),
            ],
            options={
                'verbose_name': 'Reporte Clínico',
                'verbose_name_plural': 'Reportes Clínicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteDefault',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('ver', 'Ver'), ('descargar', 'Descargar'), ('login', 'Login'), ('logout', 'Logout'), ('exportar', 'Exportar'), ('importar', 'Importar'), ('otro', 'Otro')], max_length=50)),
                ('modulo', models.CharField(max_length=100)),
                ('objeto_tipo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitosa', 'Exitosa'), ('error', 'Error'), ('advertencia', 'Advertencia')], default='exitosa', max_length=50)),
                ('mensaje_error', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_bitacora', to='seguridad_y_personal.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de Acciones',
                'verbose_name_plural': 'Bitácoras de Acciones',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', '-fecha_hora'], name='reportes_re_usuario_463e7b_idx'), models.Index(fields=['modulo', '-fecha_hora'], name='reportes_re_modulo_722caf_idx'), models.Index(fields=['-fecha_hora'], name='reportes_re_fecha_h_9118bc_idx')],
            },
        ),
    ]
