# Generated by Django 5.2.6 on 2025-11-27 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_metareporte_reporteclinico_reportedefault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteclinico',
            name='citas_completadas',
        ),
        migrations.RemoveField(
            model_name='reporteclinico',
            name='citas_reprogramadas',
        ),
        migrations.RemoveField(
            model_name='reporteclinico',
            name='tipo_cita',
        ),
        migrations.AddField(
            model_name='reporteclinico',
            name='atenciones_canceladas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reporteclinico',
            name='atenciones_completadas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reporteclinico',
            name='atenciones_en_curso',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reporteclinico',
            name='citas_confirmadas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reporteclinico',
            name='citas_pendientes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reporteclinico',
            name='citas_programadas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reporteclinico',
            name='total_odontogramas_creados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
