# Generated by Django 5.2.7 on 2025-10-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('seguridad_y_personal', '0003_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontologo', to='seguridad_y_personal.usuario'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_odontologo',
            field=models.ForeignKey(limit_choices_to={'usuario__usuariorol__id_rol__nombre_rol': 'odontologo'}, on_delete=django.db.models.deletion.CASCADE, to='citas.odontologo'),
        ),
    ]
