# Generated by Django 5.2.7 on 2025-10-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_odontologo_usuario_alter_cita_id_odontologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_odontologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.odontologo'),
        ),
    ]
