# Generated by Django 5.2.7 on 2025-10-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_id_odontologo'),
        ('seguridad_y_personal', '0004_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='odontologo_rol',
            field=models.ForeignKey(blank=True, limit_choices_to={'nombre_rol': 'odontologo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad_y_personal.rol'),
        ),
    ]
