# Generated by Django 5.2.7 on 2025-10-21 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_odontologo_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='odontologo_rol',
        ),
        migrations.RemoveField(
            model_name='odontologo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='odontologo',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
