# Generated by Django 5.2.7 on 2025-10-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_cita_odontologo_rol_remove_odontologo_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontologo',
            name='user',
        ),
    ]
