# Generated by Django 5.2.7 on 2025-10-21 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_remove_odontologo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontologo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='odontologo',
            name='username',
        ),
        migrations.AddField(
            model_name='odontologo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
