# Generated by Django 5.2.7 on 2025-10-22 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_remove_odontologo_password_and_more'),
        ('seguridad_y_personal', '0004_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='usuario_seguridad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad_y_personal.usuario'),
        ),
    ]
