# Generated by Django 5.2.6 on 2025-10-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_odontologo_usuario_seguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='matricula_profesional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
