# Generated by Django 5.2.7 on 2025-10-23 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_odontologo_matricula_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontologo',
            name='matricula_profesional',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]*$', 'Solo letras y números están permitidos.')]),
        ),
    ]
