# Generated by Django 5.2.7 on 2025-11-03 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_alter_odontologo_matricula_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Disponibilidad', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='id',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='id_disponibilidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='motivo_bloqueo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='id_odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='citas.odontologo'),
        ),
    ]
