# Generated by Django 5.2.6 on 2025-11-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_alter_disponibilidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('programada', 'Programada'), ('cancelada', 'Cancelada')], max_length=50),
        ),
    ]
