# Generated by Django 5.2.6 on 2025-11-27 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionSatisfaccion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_satisfaccion', models.IntegerField(choices=[(1, 'Muy Baja Satisfacción'), (2, 'Baja Satisfacción'), (3, 'Satisfacción Media'), (4, 'Alta Satisfacción'), (5, 'Muy Alta Satisfacción')])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_satisfaccion', to='citas.cita')),
                ('id_odontologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.odontologo')),
            ],
            options={
                'verbose_name': 'Evaluación de Satisfacción',
                'verbose_name_plural': 'Evaluaciones de Satisfacción',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
