# Generated by Django 5.2.7 on 2025-11-03 03:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0011_alter_disponibilidad_options_and_more'),
        ('pacientes', '0003_remove_archivoclinico_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_curso', 'En Curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='en_curso', max_length=50)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atencion', to='citas.cita')),
                ('id_odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='citas.odontologo')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id_odontograma', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('pieza_dental', models.CharField(blank=True, max_length=10, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='atencion.atencion')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_curso', 'En Curso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificado', max_length=50)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='citas.odontologo')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pieza', models.CharField(max_length=2)),
                ('estado', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado'), ('endodoncia', 'Endodoncia'), ('protesis', 'Prótesis'), ('extraccion', 'Extracción'), ('ausente', 'Ausente'), ('fractura', 'Fractura'), ('corona', 'Corona')], default='sano', max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('cara_vestibular', models.BooleanField(default=False)),
                ('cara_lingual', models.BooleanField(default=False)),
                ('cara_mesial', models.BooleanField(default=False)),
                ('cara_distal', models.BooleanField(default=False)),
                ('cara_oclusal', models.BooleanField(default=False)),
                ('id_odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='atencion.odontograma')),
            ],
            options={
                'verbose_name': 'Pieza Dental',
                'verbose_name_plural': 'Piezas Dentales',
                'ordering': ['numero_pieza'],
                'unique_together': {('id_odontograma', 'numero_pieza')},
            },
        ),
        migrations.CreateModel(
            name='TratamientoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True)),
                ('id_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_relacionados', to='atencion.atencion')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_relacionadas', to='atencion.tratamiento')),
            ],
            options={
                'verbose_name': 'Tratamiento-Atención',
                'verbose_name_plural': 'Tratamientos-Atenciones',
                'ordering': ['orden'],
                'unique_together': {('id_tratamiento', 'id_atencion')},
            },
        ),
    ]
