# Generated by Django 5.2.6 on 2025-11-04 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_odontograma_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
